package modelo;
// Generated 01/03/2018 14:31:04 by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private int nombre;
     private int apellido;
     private int legajo;

    public Alumno() {
    }
    public Alumno(Integer id) {
        this.id= id;
    }
    public Alumno(int nombre, int apellido, int legajo) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.legajo = legajo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNombre() {
        return this.nombre;
    }
    
    public void setNombre(int nombre) {
        this.nombre = nombre;
    }
    public int getApellido() {
        return this.apellido;
    }
    
    public void setApellido(int apellido) {
        this.apellido = apellido;
    }
    public int getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }




}


